include: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
    # - "**/model.dart"
  errors:
    avoid_print: info
    camel_case_types: warning
    unused_import: ignore
    library_private_types_in_public_api: error
    empty_constructor_bodies: warning
    avoid_renaming_method_parameters: info
    prefer_const_constructors: info

linter:
rules:
  avoid_print: true
  prefer_single_quotes: false
  camel_case_types: true
  empty_constructor_bodies: true
